cross_validation_folds: 10
n_jobs: -1
n_jobs_cv: 10
time_length: 10
path_to_data: "./data.nosync/dataset_smile_challenge_unravelled_train_cut10_stadd.npy"
gaussian_process_kernel:  # correctly accepted: matern or empty string
fusion_method: 'average' # correctly accepted: majority_voting, max, average or the following models: GaussianProcess, AdaBoost, QDA and SVM
binary: True
debug_mode: False
unravelled: True
st_feat: True
cp_all_config: True
feature_selection: True
probability: True
feature_selection_configs:
  criterion: 'mutual information' # available: correlation, mutual information, chi-square, f_classif
  method: 'percentage' # avaible are 'percentage', 'fixed number' and 'p value'
  method_attribute: 70 # e.g. percentage: 30, fixed number: 3, p value: 0.05
  joined: False
  deep_features: False
models_config:
  ECG_features: 'SVM' # available are: GaussianProcess, AdaBoost, QDA and SVM
  GSR_features: 'SVM' # available are: GaussianProcess, AdaBoost, QDA and SVM
  ST_features: 'SVM' # available are: GaussianProcess, AdaBoost, QDA and SVM
