cross_validation_folds: 10
n_jobs: 10
path_to_data: "./data.nosync/dataset_smile_challenge.npy"
missing_values_inputation: "median" # accepted_values: average, previous_val, median, most_frequent, max_val
binary: True
debug_mode: False
